programming/python/django_proj/timl/blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'

urlpatterns = [
    # post views
    # path('', views.post_list, name='post_list'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path('', views.PostListView.as_view(), name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/',
         views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
]

programming/python/django_proj/timl/timl/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
# from blog.sitemaps import PostSitemap
#
#
# sitemaps = {'posts': PostSitemap,}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('blog/', include('blog.urls', namespace='blog')),
    # path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
    #       name = 'django.contrib.sitemaps.views.sitemap')
    path('money/', include('money.urls', namespace='money')),
]

programming/python/django_proj/timl/blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager


# свой менеджер модели по работе с статьями
class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status='published')


class Post(models.Model):
    # Статусы поста
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published')
    )

    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')
    tags = TaggableManager()

    # Порядок сортировки статей
    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    object = models.Manager()
    published = PublishedManager()

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.publish.year,
                                                 self.publish.month,
                                                 self.publish.day,
                                                 self.slug])


class Comment(models.Model):
    # модель ForeignKey = сопоставляет каждый комментарий с конкретным постом
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return f'Comment by {self.name} on {self.post}'

programming/python/django_proj/timl/blog/forms.py
from django import forms
from .models import Comment


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)
    # required=False - вкл необязательное поле


class CommentForm(forms.ModelForm):
    # для работы формы, надо указать просто какую модель использовать в подклассе Meta
    class Meta:
        model = Comment
        fields = ('name', 'body')  # поля которые хотим указывать при заполнениии (есть еще 'email')

programming/python/django_proj/timl/blog/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView
from .models import Post, Comment
from .forms import EmailPostForm, CommentForm
from django.core.mail import send_mail
from taggit.models import Tag


# Обработчик вывода постов в виде класса (наследование от ListView)
class PostListView(ListView):
    queryset = Post.published.filter()
    context_object_name = 'posts'
    paginate_by = 5
    template_name = 'blog/post/list.html'

    # показывает только посты пользователя
    def get_queryset(self):
        return Post.published.filter(author=self.request.user)


def post_list(request, tag_slug=None):
    object_list = Post.published.all()
    # Сортировка по тегу, генератор ссылок
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])
    paginator = Paginator(object_list, 3) # 4-кол-во, статей на странице
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # Если страница не целое число, возвращаем первую страницу
        posts = paginator.page(1)
    except EmptyPage:
        # Если номер страницы больше, чем общее кол-во страниц, возращаем последнею
        posts = paginator.page(paginator.num_pages)
    return render(request, 'blog/post/list.html', {'page': page, 'posts': posts, 'tag': tag})


# генератор ссылок, детали постов
def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post,
                             slug=post,
                             status='published',
                             publish__year=year,
                             publish__month=month,
                             publish__day=day)
    # Список активных комментарий для данной статьи
    comments = post.comments.filter(active=True) # отображает все активные комментарии
    new_comment = None
    if request.method == 'POST':
        # Пользователь отправил комментарий
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Создаем комментарий, но пока не сохраняем его в базе
            new_comment = comment_form.save(commit=False) # commit - создает объект, но пока его не сохранаяте в БД
            # Привязываем к конкретно статье
            new_comment.post = post
            # Сохраняем данные в БД
            new_comment.save()
    else:
        comment_form = CommentForm()
    return render(request, 'blog/post/detail.html', {'post': post,
                                                     'comments': comments,
                                                     'new_comment': new_comment,
                                                     'comment_form': comment_form})


def post_share(request, post_id):
    # Получение статьи по id
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False
    if request.method == 'POST':
        # Форма была отправлена на сохранение
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # Все поля формы прошли валидацию
            cd = form.cleaned_data
            # Отправка электронной почты
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = '{} ({}) рекомендую прочитать "{}"'.format(cd['name'], cd['email'], post.title)
            message = 'Read "{}" at {}\n\n{}\'s comments:{}'.format(post.title,
                                                                    post_url,
                                                                    cd['name'],
                                                                    cd['comments'])
            send_mail(subject, message, 'acecrosser@yandex.ru', [cd['to']])
            sent = True
    else:
        form = EmailPostForm()
    return render(request, 'blog/post/share.html', {'post': post,
                                                    'form': form,
                                                    'sent': sent})

programming/python/django_proj/timl/blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% load blog_tags %}
{% block title %}{{ post.title }}{% endblock %}

{% block content %}

    <h1>{{ post.title }}</h1>
    <p class="date">Published {{ post.publish }} by {{ post.author }}</p>
    {{ post.body|markdown }}

    <p>
        <a href="{% url 'blog:post_share' post.id %}">Share this post</a>
    </p>

    {% with comments.count as total_comments %}
        <h2>{{ total_comments}} comment{{ total_comments|pluralize}}</h2>
    {% endwith %}
    <br>
    {% for comment in comments %}
    <div class="comment">
        <a class="info">
            Comment {{ forloop.counter }} by {{ comment.name }}
            {{ comment.created }}
            <br>
        </a>
        {{ comment.body }}
        <br><br>
    </div>
    {% empty %}
        <p>Пока нет комментарий</p>
    {% endfor %}

    {% if new_comment %}
        <h2>Ваш комментарий был добавлен</h2>
    {% else %}
        <h2>Добавить свой комментарий</h2>
        <form action="." method="post">
            {{ comment_form.as_p }}
            {% csrf_token %}
            <p><input type="submit" value="Отправить"></p>
        </form>
    {% endif %}

{% endblock %}

programming/python/django_proj/timl/blog/templates/blog/post/latest_posts.html
<ul>
  {% for post in latest_posts %}
  <li><a href="{{ post.get_absolute_url }}">{{ post.title}}</a></li>
  {% endfor %}
</ul>

programming/python/django_proj/timl/blog/templates/blog/post/list.html
{% extends 'blog/base.html' %}
{% load blog_tags %}
{% block title %}timl_blog{% endblock %}
{% block content %}

    <h1>.blog</h1>

    {% for post in posts %}
        <h2>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </h2>
        <p class="date">Опубликовано {{ post.publish }} by {{ post.author }}</p>
        {{ post.body|markdown|truncatewords_html:30 }}
    {% endfor %}

    {% include "pagination.html" with page=page_obj %}

{% endblock %}

programming/python/django_proj/timl/blog/templates/blog/post/share.html
{% extends "blog/base.html" %}
{% block title %}Share a post{% endblock %}
{% block content %}

    {% if sent %}
        <h1>E-mail successfully sent</h1>
        <p>"{{ post.title }}" was successfully sent to {{ form.cleaned_data.to }}.</p>
    {% else %}
        <h1>Share {{ post.title }} by e-mail</h1>
        <form action="." method="post">
            {{ form.as_p }}
            {% csrf_token %}
        <input type="submit" value="Send e-mail">
        </form>
    {% endif %}

{% endblock %}